### ISSUE TITLE
Format currencies properly

### ISSUE THREAD

**Issue by m-roberts** [shutupflanders/moneydashboard#5]
```
from babel.numbers import format_currency

# Current method
balance['net_balance'] = float(self.moneyfmt(Decimal(balance['net_balance']), 2, '', ''))

# Conceptual method to format properly
net_balance = format_currency(balances_result['net_balance'], "GBP", locale='en_GB')
```

**Comment by shutupflanders** [comment]
Before I implement something like this, are we 100% certain MoneyDashboard don't support other currencies? I don't have a Revolut to test with at the moment, but they offer separate accounts for the currencies you hold as far as I'm aware.

**Comment by m-roberts** [comment]
I don't see anything in the response that can be used to determine the currency - I would say that it's reasonable to assume GBP, and someone can submit a PR if necessary? Besides, how can a total balance be calculated if the numbers don't add up? They'd all need to be the same currency for that to make sense.
